#!/bin/sh
PATH=/usr/bin:/usr/sbin

msg() {
    # bold
    printf "\033[1m=> $@\033[m\n"
}

chvt 1

msg "Waiting for services to stop..."
svc -k > /dev/null 2>&1

msg "Saving random seed..."
( umask 077; bytes=$(cat /proc/sys/kernel/random/poolsize) || bytes=512; dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=$bytes >/dev/null 2>&1 )

msg "Stopping udev..."
udevadm control --exit

msg "Sending TERM signal to processes..."
pkill --inverse -s0,1 -TERM
sleep 1
msg "Sending KILL signal to processes..."
pkill --inverse -s0,1 -KILL

msg "Unmounting filesystems, disabling swap..."
swapoff -a &>/dev/null
umount -a -r &>/dev/null

sync
